[package]
name = "butterfly-comm"
version = "0.1.0"
edition = "2021"

[dependencies]
butterfly-core = { path = "../butterfly-core" }
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
async-trait = "0.1"
thiserror = "1.0"
